### ISSUE TITLE
Use with AS7265x 

### ISSUE THREAD

**Issue by Stefankante** [Roger-random/as7341_webui#1]
Is it possible to make this project work with Sparkfun AS7265X ? 

Thank you,
Thom

**Comment by Roger-random** [comment]
I looked over Sparkfun's product page and don't see any immediate blockers. 
https://www.sparkfun.com/products/15050

It is an I2C bus device with an Arduino library, so adapting this project should be possible. What I don't see on that page is how long the Arduino library blocks while reading the sensor, blocking the thread too long may interfere with HTTP communication with web UI. Feel free to fork this project and experiment!

Since I don't have Sparkfun's AS7265X module and don't intend to buy one, I will not be adding such capability here. This specific project will remain focused on Adafruit's AS7341 module because that's the sensor I have.
